### ISSUE TITLE
bridge2: needs to work when not running at /

### ISSUE THREAD

**Issue by ajbouh** [ajbouh/substrate#101]
When I visit `/gw/bridge2/`, bridge2 assumes that it can:
- redirect the user to /sessions or /sessions/:session.
- load /webrtc
- load /ui/...

But all of these break because they need to be properly prefixed with the base URL.

This can be available at an environment variable that's provided at spawn time.

**Comment by ajbouh** [comment]
cc @mgood

**Comment by mgood** [comment]
Does substrate pass the HTTP proxy headers about where it was forwarded from?
E.g. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded

**Comment by ajbouh** [comment]
No, but it could. What are you imagining is the right value for `Forwarded:` in this case?

**Comment by ajbouh** [comment]
We need bridge2 to know it's being served at `/gw/bridge2`, but the docs for `Forwarded:` don't provide any information about the path it was served at, just the host.

**Comment by mgood** [comment]
Yeah, I was trying to look for the equivalent of this https://werkzeug.palletsprojects.com/en/3.0.x/middleware/proxy_fix/
There's https://pkg.go.dev/net/http/httputil#ReverseProxy though it doesn't seem to set the path prefix.

**Comment by ajbouh** [comment]
What's wrong with an environment variable?

**Comment by mgood** [comment]
well, `ReverseProxy` would be on the substrate side, and then adding matching middleware to `bridge2` to parse those headers and rewrite the paths

**Comment by mgood** [comment]
#102 has most of the changes needed for this, but should probably still add an environment variable for config instead of hard-coding the path.
