### ISSUE TITLE
bridge2: sessions are not saved across service restarts

### ISSUE THREAD

**Issue by ajbouh** [ajbouh/substrate#110]
This is because substrate doesn't provide bridge2 with a long-lived directory it can write state to. We should configure it to do so.

**Comment by mgood** [comment]
@ajbouh I see a few of the Cue files list `mounts`, is there a convention for where the files for a particular service like this would go on the host system?

**Comment by ajbouh** [comment]
Those mounts are only for dev mode. They are really intended to mount source (or test) code into the containers.
