### ISSUE TITLE
bridge2: doesn't seem to support multiple inputs simultaneously

### ISSUE THREAD

**Issue by ajbouh** [ajbouh/substrate#117]
I tried using bridge2 during our comms meeting today and while it properly "heard" the other people in the call, it couldn't hear me.

We need to make it possible to send local microphone audio *and* sound from the system at the same time.

**Comment by ajbouh** [comment]
@progrium @mgood

**Comment by progrium** [comment]
Did you try two tabs?

**Comment by ajbouh** [comment]
I did not, that might have worked. I was doing a demo that included screensharing the bridge2 window itself so it was a sort of convoluted situation to start with.

I should try that next time. It's a good workaround to keep in mind, but our current demo script assumes that the same window will stream from mic and a tab. Any reason we shouldn't make that work too?

**Comment by progrium** [comment]
Nope, should be fine. We just have to make several LocalMedia instances.

**Comment by mgood** [comment]
Getting started on this. Reworking to have multiple LocalMedia instances, but the webrtc.Session also needs some work to allow multiple streams. Right now when you change streams, it replaces any tracks from the previous stream.
I guess we could also start a second WebRTC connection, though if it seems simple enough to send everything over one connection I'll aim for that first.

**Comment by ajbouh** [comment]
@mgood how'd it go?

**Comment by mgood** [comment]
I started off by adding a new session when sharing the screen, but it triggered a crash on the Go side with the buffer bounds that I need to fix.
