### ISSUE TITLE
bridge: expose apis to assistant annotator

### ISSUE THREAD

**Issue by ajbouh** [ajbouh/substrate#12]
This issue reframed to add APIs to assistant annotator. Use reflection to format available functions in prompt. We could do the current bridge assistant setup where we run input in two LLM prompts, one with functions, one without. Or we could look for a keyword like "please" or something. 

### old devlog

2023-11-06

Today my goal was to get familiar with the "function calling" capability of LLMs. While the example cases on OpenAI and the like of asking about the weather given a weather function presumably work fine, I'm very curious/skeptical how well it works with many functions to choose from, how well it can translate natural language into *intended* parameters, and how consistent/usable the output is to make those calls. 

Last week, I started looking into the bridge stack, which includes llama-cpp-python server with modifications to support functions. I got familiar with the chat/assistant packages to build a simple debug utility to test chat prompts without involving the voice recognition. Unfortunately a bad merge keeping the local changes up to date with upstream refactoring in the llama-cpp-python server made this unusable. Adam provided a diff that was supposed to fix it, but I misinterpeted it as pointing out the issue, as the diff didn't *look* like it fixed it. And I wasn't familiar enough with how any of this worked to be confident in making the fix, especially not knowing how simple it probably was. 

I turned my attention to learning more about llama-cpp-python. That it was bindings for llama-cpp, which I knew, but also a high level API server compatible-ish with the OpenAI API. In searching for the simplest way to play with models without extra layers, I found several Go bindings for llama-cpp. One of which pointed to a project built around it that also provided an OpenAI-ish API. This was LocalAI. It turned out to support multi-modal interfaces AND native function invocation. The last thing I did last week was figure out how to get it running, which it could do locally using my CPU (just slow). I got the default model to work and was excited to look into functions this week.

I started with the function API examples using the Luna AI model I got working. I was surprised it worked pretty well just with that model. I made a set of fake function schemas to play with:

- sum(a,b)
- openURL(url)
- clickElementByContent(text)
- setInputValue(name, value)
- setFullscreen(state)
- doJob()

They all had descriptions of function and parameters, which I assumed would be leaned on by the model to make a decision what to use. I mostly explored this using the Python shell and the openai package, which was compatible with LocalAI, and supported passing functions with your prompt. 

I was only a littled surprised to see "add 20 and 32" only resulted in "sum(1,2)" basically false params. However "add 20 and 32 together" and "add numbers 20 and 32" worked consistently. Seems it just needed a little more context to understand they were the params? 

The clickElementByContent function was also intended to see how well it could infer parameters. I wanted to be able to say "Click the save button", but I knew that was asking too much. Unless I was explicit about "save" being the text, it usually didn't work. Later, both models I worked with seemed to use this one as a catch all, maybe because "text" was so open ended, but I'll get to that soon.

The setFullscreen function was originally just "fullscreen" but it could never land on it. "make the window fullscreen", "call fullscreen", "fullscreen" ... none of these worked. I added "doJob" to test the idea it couldn't handle functions without parameters. It sure couldn't. But this was with the Luna AI model, so I figured maybe the Airoboros model would do better. 

Unfortunately it was an ordeal getting Airoboros to work in LocalAI. I could download the model, LocalAI lets you use model binaries without a config, but then you can't really configure them. Or provide prompt tempaltes etc. But setting it up with a config file wouldn't work. Eventually I turned debug on to see that if it was loaded with a config it assumed it was a different format, but there was no option to specify. I didn't know if it was implied by some other config. I started looking at the code and it wasn't clear it was even LocalAI that was having the issue, maybe it was llama-cpp. They error message wasn't in the LocalAI source at least. Eventually I found an example that used the old format (ggml?) instead of gguf, but then it would assume it was gguf with config. Finally I just used it without a config, since I could set temperature and prompt stuff directly in the requests. 

LocalAI unfortunately has a lot of ways to do things, which isn't helped by how many possible models, etc you can have. And the docs are... not enough. But at least the source is pretty readable. 

So now, Airoboros vs Luna ... it actually wasn't much better. It still couldn't land on functions without params. This led me to investigate the API request path and how these function definitions are used. Are they added to the prompt? I also noticed it seemed like descriptions weren't being used. 

It turns out using functions generates a grammar for the response. This grammar in BNF. This is I guess part of llama-cpp, not sure if it's something a model supports. This grammar is not included in the prompt and does not include the description. So it was purely just fitting the response to a possible function call... *except* functions with no params. I don't know if this is a bug in LocalAI's BNF generation or what, but basically turning *off* functions/grammars and just using the Airoboros suggested prompt, which includes the function schemas in the prompt works very well. 

I guess as Adam suggested, ideally we could have both. Maybe if we fix the grammar stuff it'll work even better, but I noticed there is a *huge* difference in using the functions/grammar vs not. Like you'd think it would just snap to the "closest" thing, but it just does extremely poorly a lot of the time, not just when there are no params. So as of right now, at least with LocalAI, using Airoboros gets good results without grammars and just leaning on the training and prompting to get consistent results. And now I know how this stuff works a bit better. 

I'd sort of like to make a tool/tester that has a bunch of function definitions, a bunch of user prompts that could work, and then results against different models/configurations. These probabilistic systems are super weird to work with.

**Comment by progrium** [comment]
Letting #65 take this over, closing.
