### ISSUE TITLE
bridge2: fix event display timestamps

### ISSUE THREAD

**Issue by mgood** [ajbouh/substrate#122]
The event "start" is stored as an offset from the session start, but the UI is trying to display it as just a timestamp. They need to be normalized and then formatted appropriately.
The event lists from multiple tracks also need to be merged in time order. Right now they're just being concatenated, so if you're streaming both mic and tab audio, the mic audio will be re-inserted at the top instead of in time order (since that's normally the first track initialized).

**Comment by ajbouh** [comment]
@mgood good catch! This explains what I saw while trying to test this in a browser-based zoom conference.

**Comment by ajbouh** [comment]
@mgood close?
