### ISSUE TITLE
bridge2: pegs CPUs after running for a while

### ISSUE THREAD

**Issue by ajbouh** [ajbouh/substrate#150]
Both the NUC and my Apple Silicon M3 Max machine will hit maximum possible CPU usage when running bridge2. It's unclear if it's related to sleep, broken TCP connections, or something else. No obvious error messages or log spew.

**Comment by mgood** [comment]
So you're still seeing this? I had wondered if it was related to #136 since that was re-processing longer and longer audio chunks for transcription going back to the beginning of the track. I can take a look and start to add logging or maybe profiling if needed to see what's happening.

**Comment by mgood** [comment]
Hmm, yeah usage on my M1 seems pretty high still with the latest code
