### ISSUE TITLE
bridge: session model

### ISSUE THREAD

**Issue by progrium** [ajbouh/substrate#19]
This is the next iteration of the core data model and API for bridge sessions. It allows for persistence, multiple tracks, and an annotation model for async reactive annotators such as vad, transcription, translation, diarization, assistants, etc. 

We assume sessions are created during an HTTP request to `/sessions`, redirecting to a persistent URL for the session such as `/sessions/:id`. Audio data would be received via WebRTC, and the resulting timeline to display would be pushed to the browser via WebSocket, but the core model is mostly independent of these mechanisms.

### Data model outline

Sessions have Tracks, which have Annotations. All of these have unique IDs. This data model is implemented with marshalable structs that are wrapped with a runtime API. Tracks have audio data on disk as separate audio files using the track ID in the filename. Audio coming in from WebRTC tracks is written to disk as-is and in parallel decoded into raw samples for use in memory. This iteration has no mechanism for limiting memory usage of audio data, such as windowing and reading from disk as runtime. The audio on disk is used for offline debugging and decoding back into memory when a session is used again.

Sessions have a start timestamp used to normalize times relative to the start of the session. Tracks may support other media types such as video in the future, but right now focus on audio. There is a track for every audio stream or WebRTC track ingested by the session. The Track struct contains an ID, a start time, and the audio format. During runtime it contains decoded audio samples. 

Tracks have Annotations, which have an ID, a type, optional start and end times, and type-specific data. They will eventually have versioning and provenance data, but we can introduce this later. Annotations with start/end times are global to the track. Types and type-specific data are open ended and usually associated with annotators, but there isn't a one-to-one mapping. Annotators may create or consume more than one type of annotation. 

Session structs and their tracks+annotations are written to disk as a serialized snapshot on changes for now. This session/annotation data could benefit from being stored and queryable as SQLite, but for iteration speed we can put this off. 

### API sketch

When Sessions are created you can create new tracks and push audio samples into them. The important API is what's exposed to annotators to get annotations and audio samples, how annotators are triggered, and creating annotations. All operations need to be thread-safe as annotators run in parallel. Creating annotations is just appending an Annotation struct to a collection. 

Tracks implement a Span interface, which lets you get audio samples (as a beep.Streamer) and annotations by type, as well as selecting a sub-Span by time range. You could for example get a track's word annotations (`track.Annotations("word")`) then iterate over them getting a Span for each word, filtering for Spans with a particular speaker annotation, then use their audio streamers to assemble audio samples of just one speaker. Spans also let you write annotations, filling in the start/end times based on the span and creating an ID. Here is a sketch of the Span interface:

```golang
type Span interface {
    Span(from, to) Span
    Audio() beep.Streamer
    Annotations(type) []Annotation
    Annotate(type, data) Annotation
}
```

When an annotation is created, we iterate over registered Annotators calling Annotated with the Annotation. This is a simple event trigger for annotators to react to new relevant annotations. For example, the vad annotator creates activity annotations, which the transcription annotator listens for, producing transcription annotations the translation annotator listens for, etc. 

```golang
type Annotator interface {
    Annotated(Annotation)
}
```
Annotations could have a method to return a Span for the start/end time of their track. Annotators will likely also need a reference to the session and track. Some Annotators, particularly VAD, need to react to new audio. We can model this as a pseudo annotation for now. As audio sample chunks come in, we trigger an unrecorded "audio" annotation. 

### Timeline output

The UI for a session can be based on a view model constructed from the session and its annotations on changes. This model view can be pushed to update the web UI via websocket. 

---
This issue closes #3 closes #4 closes #5

**Comment by mgood** [comment]
Alright, yeah I had a few notes, but this sounds pretty similar.
One thing I had been thinking about is a slightly more general data structure that could be used to store the annotations. The names here might need some work, but representing a kind of "map" from a range of keys to a value for that range. Could be just a linked list, or even `skiplist` for efficiency.
But mainly looking at having some more type-safety around the annotations.

```go
type Range[K comparable, V any] interface {
	Start() K
	End() K
	Value() V
	Prev() Range[K, V]
	Next() Range[K, V]
}

type RangeSet[K comparable, V any] interface {
	First() Range[K, V]
	Last() Range[K, V]
	Put(start, end K, value V)
}
```

**Comment by mgood** [comment]
From the call, some interfaces:
```go
package span

import (
	"time"

	"github.com/gopxl/beep"
	"github.com/rs/xid"
)

type Timestamp time.Duration // relative to stream start
type ID string

func newID() ID {
	// FIXME
	return ID(xid.New().String())
}

type Annotation struct {
	Start, End Timestamp
	Type       string
	ID         ID
	Data       any
}

type Session struct {
	ID     ID
	Start  time.Time
	Tracks []*Track
}

type Track struct {
	ID      ID
	session *Session
	start   Timestamp
	format  beep.Format // ?
	// End should be derived from the last audio sample?
	samples [][2]float32 // or beep buffer?
	// opus packets
	annotations []Annotation
}

func (t *Track) AddAudio(samples [][2]float32) {

}

func RegisterAnnotation[T any](typ string) {}

// func RegisterAnnotator(typ string, fn func(Annotation)) {
// 	// FIXME
// }

type Annotator interface {
	Annotated(Annotation)
}

// var _ Span = (*Track)(nil)

type Span interface {
	Track() *Track
	Span(from, to Timestamp) Span
	Start() Timestamp
	End() Timestamp
	Audio() beep.Streamer
	// I guess this returns each annotation found in the span
	// -- list annotations
	AnnotationTypes() []string
	Annotations(typ string) []Annotation
	// But this would overwrite all the annotations for the span of that type?
	Annotate(typ string, data any) Annotation
}
```

**Comment by progrium** [comment]
Today we worked out this annotation oriented API and object model for bridge. It's not perfect, but a start. Matt put in an initial implementation (https://github.com/progrium/webrtc-sessions/pull/5) and I started porting the VAD, transcriber, and diarization to hook into this API and see what changes it might need. So far so good. 

Tomorrow I'll integrate these initial annotators and port the assistant from bridge as another annotator and start getting function invocations in. But I also want to make a quick web visualizer to debug our object model. I think by end of tomorrow or Weds this design will be working end to end and we can move on to assistant APIs. But I'm expecting to work most days this week so a lot should be getting done.

**Comment by mgood** [comment]
I've filled out a bit more of the implementation in progrium/webrtc-sessions#6
This provides serialization of Session & Track via CBOR, and fills in the audio implementations to store audio with a Track, and get a subset of audio via the Span interface.

**Comment by mgood** [comment]
Today I built out some more of the model, including serialization for custom annotation types, feeding the audio stream from WebRTC into the new Track API, as well as simultaneously streaming the audio to disk.

**Comment by progrium** [comment]
Annotations are meant to capture extra "computed" information tied to spans from various services, and later the shared model might capture drafts, versions, provenance, etc .. and we can experiment with that data in the type specific data in the meantime. 

But we also need a log of events for "non-computed" inputs. Like user text input (at some point), assistant responses, commands/functions being executed, probably more. I figured a similar structure to Annotation that aren't spans, but are similarly open ended with type specific data. 

Maybe to keep it simple, we combine them? There would be events that could be at specific timestamps or be spans (zero value End), depending on the type. Annotations are just a class of event types. We'd just change some names and we'd get more out of the existing API. 

Annotation becomes Event but otherwise stays the same. Span interface becomes:
```golang
type Span interface {
        // ...
	EventTypes() []string
	Events(typ string) []Event

	RecordEvent(typ string, data any) Event // no replacing, always appends
        UpdateEvent(id string, event Event) // applies updated values to event id 
}
```
Conceptually events and annotations are ideally immutable and append-only, but annotations could be "updated" when recomputed or as a draft updates, and I want to explore that without a versioning scheme yet, so UpdateEvent is a short-term compromise.

**Comment by ajbouh** [comment]
I'm having trouble grasping this data model. I have some concrete questions:

How do we represent:
- "Voice was detected during this period"
- "Person A is speaking during these times and Person B is speaking at these other (possibly overlapping) times"
- "This long sequence of text is a transcription of that audio"
- "This word came from that audio"
- "These words are in Spanish, those words are in English"
- "This text response from an assistant was based on a context window that included these other specific messages"
- "This translation was based on that transcription"
- "This is how much silence there was between words"

**Comment by progrium** [comment]
> * "Voice was detected during this period"
VAD listens for audio, creates activity annotations. If you care about new voice activity, listen for new activity annotations. If you want all activity, iterate and get all activity annotations. 

> * "Person A is speaking during these times and Person B is speaking at these other (possibly overlapping) times"
Speaker annotations added per speaker... possibly linked to an encompassing annotation for the job that created them.

> * "This long sequence of text is a transcription of that audio"
Transcription annotations span the audio they cover, so given an annotation you get the audio for the span or given a span of audio you get the transcription annotations of the span.

> * "This word came from that audio"
Single words could be part of transcription annotation (like current bridge model) but since they are useful mapped to time, they can have their own annotations. Iterate over words in time order and you'd have spans for their corresponding audio and vice versa like above.

> * "These words are in Spanish, those words are in English"
If words have their own annotations, they can include language, probability, speaker, etc. Otherwise they'd live in their translation annotation. 

> * "This text response from an assistant was based on a context window that included these other specific messages"
Annotation data can include whatever you want.

> * "This translation was based on that transcription"
Translation annotation can keep the transcription annotation ID that triggered it.

> * "This is how much silence there was between words"
Track timespan minus summed word annotation spans.

**Comment by ajbouh** [comment]
Thanks for running through those.

Is the `Span` interface just a peculiarity of the Go API or part of the on-disk representation? Put another way, how are we storing Annotations/Events on disk and on the wire?

I'm also missing an understanding of how we get all the annotations that "overlap" with each other. How would I calculate all the languages that Jeff used during a conversation?

**Comment by progrium** [comment]
It's an API that correlates data with time. Events are just serialized structs of whatever you want wrapped with type and timespan data. 

The more arbitrary the query the more it looks like SQL like you've been hinting at. For now its just a pile of structs you can index into and relate by time.

**Comment by ajbouh** [comment]
Ok, flat records that can be correlated sounds good.

When the go out over over wire (for example to the browser) we probably want them to know their track ID (and for tracks to know their session ID), so that these sorts of "joins" are possible.

**Comment by mgood** [comment]
Finished testing and pushed some changes in https://github.com/progrium/webrtc-sessions/pull/11 to enable using the new Track model to read the audio continuously with the `beep.Streamer` API. It also adds some synchronization where needed in handling the audio buffer, as well as removing the need for `beep.Dup` which would have needed synchronization as well.

**Comment by progrium** [comment]
Closing and making separate issues for any iterations.
