### ISSUE TITLE
bridge: assistant configuration

### ISSUE THREAD

**Issue by mgood** [ajbouh/substrate#190]
#64 included an interface for adding assistants to a session, but I think there's still some detail missing in terms of how we want to configure those.
The prior implementation used env vars to configure name & url, but the system prompt was fixed.
Are we ok with a semi-static configuration that's passed in at startup time? E.g. we can keep the env vars at least for the names, though size limits might restrict the usefulness of passing prompts in the environment. So maybe injecting files with the prompt contents?
Or do we expect to configure the assistants dynamically at runtime? We could conceivably use voice commands to add an assistant, though it may be challenging to dictate accurately, and if we want to reuse the same prompt again we'd want a more central way to store the common prompts.
Though for dynamically adding assistants we could consider storing them as an "event" to record adding an assistant to the session. Then if we reload the session we re-add that assistant from the event log.

**Comment by ajbouh** [comment]
Yes, we expect to add assistants at runtime. We also expect the main assistant (named bridge) to add and remove other assistants on the fly.

I think storing the prompts as separate files in the session directory makes the most sense. We might want to switch to giving each session its own base directory.

We can record which prompt we used in the session file as we detect and use it, but leave the "current" prompt as a standalone file. This makes it easy for other tools to integrate with what bridge is doing without requiring a large and more complex API surface area.

**Comment by mgood** [comment]
Got started on add/remove assistant last night, should have a PR up soon
