### ISSUE TITLE
accessing bridge

### ISSUE THREAD

**Issue by yoshikiohshima** [ajbouh/substrate#37]
I get 502 "Bad Gateway" when I run ngrok on my MacOS to forward https request to the NUC computer. when I run a command like `find . -name start.ef83bcd7.js -print` I get the file located in `/run/media/oob/.../diff/...` but it also says that `find: File system loop detected; /sysroot/ostree/deploy/... is part of the same file system loop as ...`. That to me sounds like the reason why the web server cannot respond with the file content.

**Comment by ajbouh** [comment]
Please try the latest instructions, this should be fixed now!
