### ISSUE TITLE
bridge: session events

### ISSUE THREAD

**Issue by progrium** [ajbouh/substrate#46]
This is a few updates to the session model:

## Event type

From the [comment](https://github.com/ajbouh/substrate/issues/19#issuecomment-1887874194) in #19 we want a variation on Annotations called Events, which are Annotations without End times. We could just generalize Annotations to Events to simplify, but I'll leave this to implementor. Either way, this would update the Span interface to have:
 
```go
type Span interface {
        // ...
	EventTypes() []string
	Events(typ string) []Event

	RecordEvent(typ string, data any) Event // no replacing, always appends
        UpdateEvent(id string, event Event) // applies updated values to event id 
}
```
UpdateEvent is really only needed if we generalize, otherwise this is only needed by Annotations, so it could be UpdateAnnotation.

## Change signaling

Annotators can just become change handlers, since we also need session level change events (for disk snapshots and ui updates). Session can embed something like this simple EventEmitter model:

```golang
type Handler interface {
	HandleEvent(e Event)
}

type EventEmitter struct {
	m sync.Map
}

func (ee *EventEmitter) Listen(n Handler) {
	ee.m.Store(reflect.ValueOf(n), n)
}

func (ee *EventEmitter) Unlisten(n Handler) {
	ee.m.Delete(reflect.ValueOf(n))
}

func (ee *EventEmitter) Emit(e Event) {
	ee.m.Range(func(k, v any) bool {
		if h, ok := v.(Handler); ok {
			h.HandleEvent(e)
		}
		return true
	})
}
```

**Comment by mgood** [comment]
Hmm, combining Event and Annotation does seem reasonable, though is there a reason to keep the Event with "no end" vs having the Event `Start == End` to represent an instantaneous event vs one that spans some longer time range?

E.g. when filtering the events/annotations that occurred during a Span, it feels more consistent to say that it starts and ends at the same instant, and therefore falls either inside or outside of the Span.

I think that would also generalize more easily to recording the events vs annotations.

I.e. it sounds like with the proposed interface, this would record an event I assume at the start-time for the span, but with no end?
```
track.Span(10, 20).RecordEvent("foo", "bar")
```
But then we'd need some different method for adding annotations which do have an end. But if we make events `Start == End`, they can be recorded without any real changes to the structure:
```
track.Span(10, 10).RecordEvent("foo", "bar")
```

**Comment by progrium** [comment]
You're right, that sounds good to me.

**Comment by mgood** [comment]
Maybe since `UpdateEvent` is on the Span, then it should probably also update the Event to match that Span?
E.g. `UpdateEvent(id ID, data any)` instead, and then it changes the data and start/end times?

**Comment by mgood** [comment]
Pushed this change to handle the rename https://github.com/progrium/webrtc-sessions/pull/12
Will add the event emitter too
