### ISSUE TITLE
bridge: session history UI

### ISSUE THREAD

**Issue by progrium** [ajbouh/substrate#48]
You can now see a very simple list of previous sessions in the sidebar. However, we only have the session ID to identify it which is not super friendly. Sessions should have a name or summary field. But what should it be set to?

### Step 1: default is the date
Pretty straightforward, easy first pass. 

### Step 2: LLM generated
Once we have server side text transcript of timeline, we can just pass it to assister and ask for a short sentence summary. Inspired by what I assume ChatGPT does for their session titles.

### Step 3: user specified
Let the session header in the topbar be editable. Depends on duplex to make calls like this from the frontend more easily.

**Comment by progrium** [comment]
To save time, I'd close this after step 1 and revisit the others when painfully necessary.

**Comment by ajbouh** [comment]
Yeah works for me
