### ISSUE TITLE
bridge: diarization service setup

### ISSUE THREAD

**Issue by progrium** [ajbouh/substrate#62]
There is a WIP dir under services for diarizer that is mostly a copy of the transcriber service. We need to pull the code from `cmd/minibridge/diarize` and set it up as a web service. It also needs a test audio file, I recommend finding a public conference call on YouTube like this [GitLab product meeting](https://www.youtube.com/watch?v=lBVtvOpU80Q&t=2011s) and using a subset of that with multiple speakers. 

Make a note of memory usage and image size for the readme.

**Comment by ajbouh** [comment]
https://github.com/progrium/webrtc-sessions/tree/main/cmd/minibridge/diarize

**Comment by mgood** [comment]
I think this is basically ready, I'm just working on getting a better audio sample with various speakers, but not too long.
