### ISSUE TITLE
bridge: port assistant package to assistant agent

### ISSUE THREAD

**Issue by progrium** [ajbouh/substrate#64]
Using the old assistant package in substrate bridge as a reference, we need to port this to a minibridge agent. This was originally used for two purposes: choosing functions to invoke, and generally just getting LLM conversational responses. This was done by sending two requests to the LLM service, one with function definitions and one without. We will probably do something similar but I want to separate out the function invocation as a separate issue to do after this one because its more involved with registering functions and defining schemas.

In this version, though, we want to support multiple assistants as they can be created on the fly. There is an initial "bridge" assistant that is always available. Data model looking something like:

```golang
type Agent struct {
  // ...
  Assistants []Assistant // could be a map even, needs mutex either way
}

func (agent *Agent) AddAssistant(name string, prompt string) error { }
func (agent *Agent) RemoveAssistant(name string) error { }

type Assistant struct {
  Name string // name used to identify
  Prompt string // system prompt or prompt template
}

func (*Assistant) Chat(input string) error { }
```

Assistant would also have Commands but that comes later. The Agent event handler listeners for transcription events and checks the first word against assistant names and then calls Chat with the rest of the text. For now all assistants use the same service (assister/localai) and model.

The old assistant package would also grab recent timeline history (excluding responses from other assistants), and we will eventually want to do this for context. However, we can do that in a separate issue because this will depend on generating a text transcript / timline server side, which we are not yet. 

Assistant responses are added as events, for now on the track that triggered it. These would also need to be processed on the frontend and added to the model view to show up in the session timeline.

**Comment by mgood** [comment]
Starting on this, I'm putting together a bit of test code as well to make it a little easier to prototype without going through the actual speech recognition to trigger everything.

**Comment by ajbouh** [comment]
We have some test code already, are you using that?

**Comment by mgood** [comment]
> We have some test code already, are you using that?

The stuff you’re referring to is higher level like integration testing right? This is just some smaller helper code for doing more like unit testing of the bridge2 event handlers.

**Comment by ajbouh** [comment]
Got it, yeah I was talking about the assister test itself. If what we have is not easy or straightforward to use please tell me and I'll help fix it.

**Comment by mgood** [comment]
Based on conversation with Adam, we'll look for the assistant name anywhere in the message, not just the first word.
But we'll only send the current message where it occurred for now.
