### ISSUE TITLE
bridge: commands for assistant agent

### ISSUE THREAD

**Issue by progrium** [ajbouh/substrate#65]
This is a continuation of the assistant agent in #64 for commands. There are several parts:

### Defining commands

Commands are per assistant, but since assistants can be made on the fly, there isn't a great way to associate commands with them other than by name. We'll go with that for now, which works for the bridge assistant since its builtin. We can experiment with other assistants that have commands by just naming them based on the name used to register the commands until we come up with something better. 

Commands are just wrapped Go methods, but we need metadata to generate descriptions for the LLM. Commands live on component defined with `assistant.CommandProvider` interface:

```golang
type CommandProvider interface {
  AssistantCommands() []Command
}

type Command struct {
  Assistant string // name of assistant its for
  MethodName string // method name on CommandProvider instance
  Description string // method/command description
  Parameters []Parameter
}

type Parameter struct {
  Name string // name of parameter
  Description string 
  Required bool
  Type string // JSON type that can be converted to type used by method argument
}
```

The assistant.Agent can collect these Providers via `engine.Run`, it just needs a field. We should also be able to get them by assistant name.

```golang
type Agent {
  // ...
  CommandProviders []CommandProvider
}

func (*Agent) Commands(assistant string) []CommandProvider {}
```

### Detecting/choosing commands

In the Agent event handler, if an assistant is invoked by name and there are commands for that assistant, we perform a chat completion call to the assister service with a special prompt template that includes the commands:

```
As an AI assistant, please select the single most suitable function and parameters from the list of available functions below, based on the user's input. Provide your response in JSON format.

Input: {.Input}

Available functions:
{.Functions}

Response:

```
This template has been used and tested against the airoboros model included in the assister service. The format of the Functions passed to it looks like these examples but encoded as YAML (which it has been trained against for this purpose):
```
{
  "doJob": {
    "description": "perform the job",
    "parameters": {}
  },
  "sum": {
    "description": "Adds two numbers together",
    "parameters": {
      "a": {
          "type": "number",
          "description": "the first number",
          "required": True
      },
      "b": {"type": "number", "description": "the second number", "required": True},
    },
  },
  "openURL": {
    "description": "opens a URL to a website",
    "parameters": {
      "url": {
        "type": "string",
        "description": "the URL to open",
        "required": True,
      }
    },
  },
  "setFullscreen": {
    "description": "make the browser fullscreen or not",
    "parameters": {
      "state": {
          "type": "boolean",
          "description": "whether to make full screen or not"
        }
    }
  },
  "addAssistant": {
    "description": "adds an assistant with a name and behavior prompt",
    "parameters": {
      "name": {
          "type": "string",
          "description": "name of the assistant"
        },
      "prompt": {
          "type": "string",
          "description": "full description of how the assistant should behave"
        },
    }
  }
}
```

This should always result in a selection, even if its wrong. I'm not sure the best way to select command result or chat result, perhaps just another LLM query! For now, if there are commands for an assistant, we use the resulting command. This means for now the builtin bridge assistant only performs commands, but will include commands to add assistants, which can then be used for regular chat completions.

### Invoking commands

We want to log proposed commands to the session as an event. The UX for executing these commands is TBD, but likely there should be some user interaction, like approving the command. We can do this once we have better two-way communication with frontend (duplex). The proposed command could be presented as JSON with an Approve or Deny button. Alternatively or in the meantime we can approve or deny by voice: the agent event listener listens for transcripts, checking for a command proposal as previous event, and just looking for "approve" or "deny". 

Either way, the Agent struct needs a method to invoke the proposed method against the command provider using go reflection. For now, the result is serialized and logged as an event to show in the timeline. Later iterations can use LLM to describe the result more naturally.

### Initial commands

The Add/Remove assistant commands on Agent defined in #64 are good initial commands, so `assistant.Agent` would be a `CommandProvider` itself. Here are example user inputs that should create assistants as discussed from #9:

"add an assistant named pat. it should employ the socratic method in conversation, but only when the user seems to be stumped."
"add an assistant named alex. it should act as an investigative journalist to understand what happened in my day and how i felt about it."

The final example command JSON previously of "addAssistant" was tested against these inputs, so it can be used for reference in the command description.

### See also

See also closed issue #12 for some background on getting function "choosing" to work.

**Comment by mgood** [comment]
@ajbouh from the video chat we had a while back I believe you had some feedback on how the prompts should be expressed. Do you have specific examples of what format they should take?

A couple things we'd need to address:
What should the message format look like? Do we need to distinguish a "command" input from other assistant inputs? Or how do we decide what prompt format to send when attempting to resolve a command.

Does this prompt format and function spec seem ok, or do we need to make changes.

It sounds like Jeff may have done some experimentation with those inputs, so I could go ahead and try it, but just wanted to make sure I'm not heading down a dead end if you had concerns.

**Comment by mgood** [comment]
Ok, after our call, it sounds like the current plan will be:
Start with exposing a JS API following the conventions from chromestage for commands.
Can invoke this directly from the debug tools in the browser.

Adding an assistant will take just "name" and "system prompt" as text inputs.

We'll switch to using the "completion" API based on this instead of "chat completion" in order to have more control over the format:
https://github.com/sashabaranov/go-openai/blob/master/completion.go

Add a Go template to control the input to the completion prompt. We should be able to live-edit the template file to quickly test prompt changes. (Adam mentioned using the text transcript template as a reference)

**Comment by mgood** [comment]
Can look at this
https://huggingface.co/FoxEngineAi/Hermes-2-Pro-Mistral-7B_AWQ-GEMM_4_128_True#prompt-format-for-function-calling
