### ISSUE TITLE
bridge: assistant api for stages

### ISSUE THREAD

**Issue by ajbouh** [ajbouh/substrate#7]
This API would be exposed to assistant LLM via reflection:
```golang
type StageAPI interface {
    CreateStage() (int, error) // create new chromestage instance
    CloseStage(id int) error // close chromestage instance

    OpenURL(id int, url string) error
    OpenBlank(id int) error

    // high level raw dom operations, presumably on blank page
    AppendParagraph(id int, text string) error
    AppendImage(id int, url string) error

    CastStage(id int, dest string) error // requires setup, via functions? config?
    ...
}
```
An initial version can act on a single stage, so stage id management isn't necessary. Initially we'll just hit the Docker API directly to spawn a chromestage instance for each stage and keep a chromedp connection to it.

**Comment by ajbouh** [comment]
no need to hit the docker API directly, since this is what substrate already does for us

**Comment by progrium** [comment]
rolling into #10

**Comment by ajbouh** [comment]
For some reason I never answered this question. Sorry.

Correct, any HTTP requests to `/gw/foo/*` will launch the foo service (which by convention should be defined in `foo.cue` and have a `Dockerfile` in `/images/foo/`)

The container is started with a `PORT` environment variable. Substrate polls this port until it accepts a connection. After that, all requests requests will be reverse proxied to the container.
