### ISSUE TITLE
bridge: assistant api for assistants

### ISSUE THREAD

**Issue by ajbouh** [ajbouh/substrate#9]
```golang
type AssistantAPI interface {
    AddAssistant(name string) error
    RemoveAssistant(name string) error
    ...
}
```

**Comment by ajbouh** [comment]
Assistants have at least a name and a "system prompt". They might also have an underlying model name.

**Comment by progrium** [comment]
This isn't a model of an assistant, but what you'd need to add/remove by voice.

**Comment by ajbouh** [comment]
Right, so the command would be something like ...
- "add an assistant named pat. it should employ the socratic method in conversation, but only when the user seems to be stumped."
- "add an assistant named alex. it should act as an investigative journalist to understand what happened in my day and how i felt about it."

**Comment by progrium** [comment]
will continue as part of #65
